[package]
name = "kiroshi"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "WIP"

[workspace]
members = ["desktop"]

[workspace.dependencies]
kiroshi = { path = "." }

bytes = "1"
dirs = "6"
futures = "0.3"
iced = { git = "https://github.com/iced-rs/iced.git", rev = "ca61706cfd9da6306626793443f90ad2bf2dab51" }
num-traits = "0.2"
rand = "0.8"
serde = "1"
serde_json = "1"
tokio = "1"
toml = "0.8"

[dependencies]
bytes.workspace = true
dirs.workspace = true
futures.workspace = true
num-traits.workspace = true
rand.workspace = true
serde_json.workspace = true
toml.workspace = true

serde.workspace = true
serde.features = ["derive"]

tokio.workspace = true
tokio.features = ["process", "net", "io-util"]
